application: jason-apicall
version: live
runtime: php
api_version: 1
threadsafe: true

handlers:
- url: /
  script: riotapicall.php

- url: /currentgame
  script: currentgame.php

- url: /curltest
  script: curltest.php

- url: /riot.html
  script: riot.html